---
on: 
  push:


jobs:
  createmaps:
    runs-on: ubuntu-latest
    steps:
      - name: pull docker image
        run: docker pull ghcr.io/xcsoar/mapgen-worker
      - name: run mapgen-worker and produce maps
        run: docker run --mount type=bind,source="$(pwd)",target=/opt/mapgen/data ghcr.io/xcsoar/mapgen-worker /opt/mapgen/bin/generate-maps
